language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk7
  - oraclejdk8
notifications:
  email:
    - ansell.peter@gmail.com
after_success:
  - mvn clean test jacoco:report coveralls:report
